-- Run once in Supabase → SQL Editor.
-- Tabel voor houdbaarheid / THT (los van Realiteit-voorraad).

create table if not exists public."Houdbaarheid" (
  id bigint generated by default as identity primary key,
  product text not null,
  tht_datum date not null,
  ingevoerd_op date not null default (timezone('Europe/Amsterdam', now()))::date,
  created_at timestamptz not null default now()
);

alter table public."Houdbaarheid" enable row level security;

-- Policies voor anon (zelfde patroon als Realiteit)
drop policy if exists "anon_select_Houdbaarheid" on public."Houdbaarheid";
create policy "anon_select_Houdbaarheid"
on public."Houdbaarheid"
for select
to anon
using (true);

drop policy if exists "anon_insert_Houdbaarheid" on public."Houdbaarheid";
create policy "anon_insert_Houdbaarheid"
on public."Houdbaarheid"
for insert
to anon
with check (true);

drop policy if exists "anon_delete_Houdbaarheid" on public."Houdbaarheid";
create policy "anon_delete_Houdbaarheid"
on public."Houdbaarheid"
for delete
to anon
using (true);

drop policy if exists "anon_update_Houdbaarheid" on public."Houdbaarheid";
create policy "anon_update_Houdbaarheid"
on public."Houdbaarheid"
for update
to anon
using (true)
with check (true);
